### PR TITLE
Prevent updating tenant ID

### PR DESCRIPTION
**Pull request by taion**
Need tests.

### CODE REVIEW

**Review by itajaja — COMMENTED** [review]
Shouldn't this at least be easily skippable? there are some use cases where this is legit

**Comment by taion** [comment]
Yeah, so then you override it and do:

```python
def check_update_item_tenant_id(self, item, data):
    pass
```

**Comment by itajaja** [comment]
eh, sure. ok

**Comment by taion** [comment]
idk, is there a better way to do this? or when do we even allow changing item tenant ID?

**Comment by taion** [comment]
Good to go now.

**Review by itajaja — APPROVED** [review]

**Comment by itajaja** [comment]
I think this is OK

**Pull request merged**
